- name: Install and Configure Node Exporter
  hosts: test
  become: true
  vars:
    node_exporter_version: 1.6.0

  tasks:
    - name: Download Node Exporter archive
      get_url:
        url : "https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz
        mode: 0644
      
    - name: Extract Node Exporter archive
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp
        remote_src: yes
      
    - name: Move Node Exporter binary
      command: 
        cmd: mv /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/
        creates: /usr/local/bin/node_exporter
      
    - name: Create Node Exporter user
      user:
        name: node_exporter
        system: true
        shell: /bin/false
      
    - name: Create Node Exporter service file
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0644
      
    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes

